format = """
[â•­â”€\\($username$hostname\\)â”€\\[$directory\\]$git_branch$git_status$cmd_duration](white)
[â•°â”€](white)$status[ï„…](bold red)[ï„…](bold green)[ï„…](bold yellow) 
"""

add_newline = false

[directory]
style = 'bold white'
format = '[$path]($style)'
truncation_length = 5
truncation_symbol = ''

[git_branch]
style = 'bold red'
format = 'â”€\([$branch]($style)'

[git_status]
style = 'yellow'
format = '( [$modified$ahead_behind$renamed$untracked$staged$conflicted$deleted]($style))\)'
conflicted = '='
ahead = 'â‡¡'
behind = 'â‡£'
diverged = 'â‡•'
up_to_date = ''
untracked = '?'
stashed = ''
modified = '*'
staged = '+'
renamed = 'Â»'
deleted = 'âœ•'

[cmd_duration]
min_time = 10_000
style = 'bold yellow'
format = 'â”€\[[$duration]($style)\]'

[status]
style = 'red'
format = '\([$int]($style)\)'
disabled = false

[username]
show_always = true
style_user = 'bold blue'
style_root = 'bold red'
format = '[$user]($style)'

[hostname]
trim_at = '.'
ssh_only = true
ssh_symbol = 'ğŸŒ'
style = 'bold blue'
format = '[@$hostname $ssh_symbol]($style)'